sudo: false
dist: trusty
services:
- docker
before_install:
- sudo apt-get -y update || true
- sudo apt-get -y install cgroup-bin curl
- curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.1/lando-v3.0.0-rc.1.deb
- sudo dpkg -i /tmp/lando-latest.deb
- lando version
- lando start -- -v
- composer global require pantheon-systems/terminus:^1.9.0
install:
- lando composer install
script:
- lando composer prepare-for-pantheon
- lando terminus auth:login --machine-token=$PANTHEON_TOKEN
- lando pull --code=none --database=dev --files=dev --rsync
- lando terminus backup:get ibm-dte.dev --element=db --to=/app/database.sql.gz
- lando db-import database.sql.gz
- cd web
- lando drush cr | grep "rebuild complete."
- cd ..
before_deploy:
- git remote add pantheon $PANTHEON_GIT
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/travis/deploy.sh
  on:
    branch: master
after_script:
- lando terminus ssh-key:remove $(ssh-keygen -l -f ~/.lando/keys/pantheon.lando.id_rsa.pub
  | awk -F' ' '{print $2}' | sed 's/://g')
env:
  global:
  - secure: yR9tScYLwBITWGlXVDjeY8/JTVxlnMRn5rYnHBsMLiIbXzs5GUR/nfkvPIzyNbG1tFYaS7bHGidnI6bvPeqVTjl2rII9yOWmio6604uachFnUCkxBb++fRfA/GXYE+Wk9D6pkMn6GmOA92aldaxsAsyYb9KQtwk4PIJwetLOSKVmLN64oytrj9rfVFX7cIEB2jvcwYf94gVgw/UTlOIRLRAEZfuBlH2TmJjBwf51lO2PiHEL9TCQoryk1EifxZjg1LynZ7TFajMh7c9MH5SVMRrIXRwijrDj7P0ZELn0PS5NYHSGdtKlmeAho4KO7zizRJ++lWKT2LbPf2V8QD+yFW/OYp3oXHgnPgIh9oc4HGsy2Qsd+8Ry9eY9t115eNAn95kEl1dDBH67QSbFL1SDjEJ6rFOKzBfHY1aeav03PHno0Ui9WDO3IDXZMnm5jqY0indQUIrXGRSHnyUFMTxswfM95Rgsn9aa6M5Z+YDYs45Iiblco18KD0CA4H4yz21jBz6JFwr2Ft/1NixSCz8tfJ8m1f1nfO3JtT29qIA0xWLS7+RvS+d/hkkeNCO2dDvYku+k//jHE1YWIdZE3g3FF6IIJmdcEBNfcUpRPTK22KIM+gcElpS1DI1Lf0IhqIW2nZs3HCLT+e+6fvSR/oM0en70GYGKbKtMTxBX5hJGw2Y=
  - secure: HNe2s9VhRvraI2mVSEQM+BXjPzRodl99mn1mQQIHFwikyedMz5+M61Uynr99o7WOwfHGDs1V/Z7kzxS7d58IjpHf3hTZ78fY2J1aKIUJVo3JGr3iz4Zgv/pPzYW7hDcStSyN1KpRIPsazf/8qg5i8v2FXe21yF6BP7KNP6H3YtW3xYV4kLtzFSz5JWwcmwW18SDVOsG/0l5hozbplMVLiDIc4rxmArsTI6BKl4s3TndsfjZpTz8YBZ5z/aZTBBVI4mN+wud4ZwHuV5230BMz4erMZUbgSpIxWXV1O/yT5L5ejNXHWgZyhFBwpkGPpeArZlDonn7V/VP9lwErYsRbLrd666RVeve93R5DzVsCi17bdM7GVrjWuE4CNhhviCx5omR+1Cokn0c2sL5cULDfc5OkPNN6jp3VLSuhsSGJobTFwRa7NkUVChSBKeInYomrkGK3wufq7Aycz2pL1JANVgy0RWa4rtRai847zH2gjRzqrampy+iic5N4oQdHlzqHC7nTxTKko1d4ssvLQd9LjrZSPc1d0/+Im2l1oeuRn9hNedtYNbiMDGhf5TUTiiEabxR+7dP/8psgOR33ZMHdFfBWAGX8jLE78FKojgSF95dSmvXpWH68u9WKIBHvrGc3hMsPSz3IdvYP8m9nD+wnRYtLvRJN2L3H/barhnSqeRI=
  - secure: HpbSzMLscNnS9No8G1mij9vBNCBN/3gUC++TAEQfkem+HKuqF+Wm3abEtMwuuIH9I6D3VhkA1CWmB5ald1CxRAHnB2d3ZUihqgNpC4H8Zbe87Ek0Rg8zRbiCoQ5+D4dfYkLSSFnW3PzSxli3B5wuNJFg1wghT/Pwf0bS03L1BKmtCm3bkpmN1C3iSys5C7tckWGuPvP97Od6jy/vwRZIBw6in6vqBqua9/zoUvYbcXCNTuNCXkbRG110hzUDfqgLiake8GIK+Y2WVXQ96pBuoVFxW7vfwGGFoB68a5i9s8FVeqseS/w9cjSbt9xNlrtKbrE0gEqKgmLptl3OrXsblI2itHWqlbkNurv/HyNBHa6QDxyWx9c5OZtMGkETtNhhMCwNZ6ouoHSY6Db1mo+bNYHEOToaycNIl9Fta3bq2zh/y/ME8d424A8UBW7JYo+X3c+dQRxzoWaNIor9liJet6/7rSiHkneIJBKhGdTgE3dN3JSq4iBwJw85+LrYVp9JJE4wKdY0J16Y/1/13osPCrGE2BDH7SKActwr3N+hCBTyos1pMaTp3mpeSWYZkl5x69hta3yhWJcBW8z6SSxwNy8IUXHH5/SCu95YbaOx2z67Q8fTJmHlthLJwSA9RriRZ7Ly4/IJlIXbcEaQ/BRQflxUae5m3p+NJsfOzWP80v8=
notifications:
  email: false
  slack:
    secure: sMddqvtYmjXfiKGxPa/jnvbaBkIXozaKQGF6p37S9n/z9CMF4SAaKmRqWXssvUloP/5BKAnrlRMLs3zvnZOeScn716k4TU5wMS7dGSdZdDUejCVoh2ggCBTMKrWm1J6bjVhSS+E+1AE9IO9VetUH3veTFwgi/bDDpL1Iqde1lAmYhkAjcD755r1IMBTwk530cxjcEoUtUQRcZ2UivCFtT5h8i0JpJyTOxJUS/B6YbEel58TcqRO9xUWspI8LCG78LwmtrBuxD34VjKOzUoESgwOJUv3N6XxuUZEaPybN6qfVnT9X1OoMFisBmivrIb9WKDQfJotuWnuO7wX7aZ9vlUsFF7S4eRMkRPZrCmyvPTKZtzavKwpbotCjy8OkjuAitYeJkGQqmG4BOKHktVfLtQxtQUAbQMnylqki/HO3BTjAWQw6VUJhLMBmCrMVrzXfdlH/X7lj0G1qx3yqX1jG0QdbBnxh1d4CDZPrdyFq9MI9fylJUow9JOxSMs46QXUoTyOTxS/ujTJ4yruI0EhtGlXHo3Syh9IFWUdJYVW+UNvYdMQifhuQPCmfJvxGEUh871aOGnm1YfB1eZVJRiw/ERLRri3x4cAfEj3/W+64CTVL6SAczz5P8grIw+WA92KhWRIrn2mtPQ1SJ7NSg5e+KlCtLrOVLAyXcvWspDa6SUU=
