module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_uploadimage: 0
  codesnippet: 0
  coffee: 0
  conditional_fields: 0
  config: 0
  config_direct_save: 0
  consumers: 0
  content_moderation: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  disable_html5_validation: 0
  dpl: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_embed: 0
  entity_reference_revisions: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  fieldable_path: 0
  file: 0
  filter: 0
  gm_addons: 0
  image: 0
  inline_form_errors: 0
  jsonapi: 0
  jsonapi_extras: 0
  key_value: 0
  language: 0
  layout_discovery: 0
  link: 0
  maxlength: 0
  media: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_multilingual: 0
  moderation_note: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  plupload: 0
  plupload_widget: 0
  redirect_after_login: 0
  search: 0
  serialization: 0
  statistics: 0
  structure_sync: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  workbench: 0
  workflows: 0
  youtube: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  material_admin: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
