module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  config: 0
  config_direct_save: 0
  content_moderation: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  inline_form_errors: 0
  jsonapi: 0
  jsonapi_extras: 0
  language: 0
  layout_discovery: 0
  link: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  search: 0
  serialization: 0
  statistics: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  workbench: 0
  workflows: 0
  youtube: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
