supported_entity_types:
  - node
  - taxonomy_term
  - comment
  - menu_link_content
  - block_content
  - file
  - media
  - shortcut
  - entity_test
  - entity_test_rev
  - entity_test_mul
  - entity_test_mulrev
  - entity_test_local
  - content_moderation_state
  - replication_log
  - paragraph
  - paragraphs_library_item
  - crop
  - poll
  - poll_choice
  - redirect
enabled_entity_types:
  - content_moderation_state
  - file
  - media
  - node
  - taxonomy_term
  - menu_link_content
  - replication_log
_core:
  default_config_hash: 6_asT1b4YxagkCEkp5UI1S6MlT9k4Ffb4gc5r6uCksU
