id: basic_policy
label: 'Basic policy'
password_reset: 90
langcode: en
policy_constraints:
  -
    id: character_types
    character_types: 3
  -
    id: password_length
    character_length: 8
    character_operation: minimum
  -
    id: password_policy_history_constraint
    history_repeats: 0
roles:
  authenticated: authenticated
  content_creator: content_creator
  technical_reviewer: technical_reviewer
  content_editor: content_editor
  manager: manager
  translator: translator
