roleassign_roles:
  content_creator: content_creator
  technical_reviewer: technical_reviewer
  content_editor: content_editor
  translator: translator
  manager: '0'
  api_consumer: '0'
  api_consumer_staging_: '0'
  administrator: '0'
_core:
  default_config_hash: iKucdYPrf1EPMz6Y3s71EADiRcAiwoLTIw9_JoxH-Jg
