taxonomies:
  portfolios:
    -
      vid: portfolios
      tid: '1'
      langcode: en
      name: 'Hybrid Data Management'
      description__value: null
      description__format: null
      weight: '37'
      parent: '0'
      uuid: a91e6d68-20ef-41f2-9e19-cf00d245a48a
    -
      vid: portfolios
      tid: '2'
      langcode: en
      name: 'Integration and Development'
      description__value: null
      description__format: null
      weight: '41'
      parent: '0'
      uuid: 0364594e-2a76-4a05-a137-d455b5c80634
    -
      vid: portfolios
      tid: '3'
      langcode: en
      name: 'Management and Platform'
      description__value: null
      description__format: null
      weight: '19'
      parent: '0'
      uuid: 07a481dc-675e-433f-8777-07841331e02f
    -
      vid: portfolios
      tid: '4'
      langcode: en
      name: 'Unified Governance and Integration'
      description__value: null
      description__format: null
      weight: '17'
      parent: '0'
      uuid: b0678f24-e5e4-4a53-b36f-eac2dfd9b0fe
    -
      vid: portfolios
      tid: '5'
      langcode: en
      name: 'Data Science and Business Analytics'
      description__value: null
      description__format: null
      weight: '22'
      parent: '0'
      uuid: b463eb13-ef0a-416e-b1ed-70ff8f3fbfa0
    -
      vid: portfolios
      tid: '6'
      langcode: en
      name: 'Watson and Cloud Platform'
      description__value: null
      description__format: null
      weight: '13'
      parent: '0'
      uuid: 86d4ffb1-e3ad-48bb-af95-21d948b041d7
    -
      vid: portfolios
      tid: '7'
      langcode: en
      name: 'Digital Business Automation'
      description__value: null
      description__format: null
      weight: '33'
      parent: '0'
      uuid: 28ddf914-d380-46bf-9172-e0183c71b722
    -
      vid: portfolios
      tid: '9'
      langcode: en
      name: 'IBM API Connect'
      description__value: null
      description__format: null
      weight: '4'
      parent: '2'
      uuid: df2816da-f27e-4188-9d98-e6a4370423d2
    -
      vid: portfolios
      tid: '10'
      langcode: en
      name: 'IBM Cloud Private'
      description__value: null
      description__format: null
      weight: '0'
      parent: '3'
      uuid: e68a5a6e-1749-4001-844d-a9c94519ff63
    -
      vid: portfolios
      tid: '11'
      langcode: en
      name: 'IBM Master Data Management'
      description__value: null
      description__format: null
      weight: '1'
      parent: '4'
      uuid: 3b78291e-199c-4d4a-ab04-18a7ff81b86a
    -
      vid: portfolios
      tid: '12'
      langcode: en
      name: 'IBM Data Science Experience Local'
      description__value: null
      description__format: null
      weight: '2'
      parent: '5'
      uuid: 8a138be6-a01d-4386-8720-3d705851d31e
    -
      vid: portfolios
      tid: '13'
      langcode: en
      name: 'IBM DataPower Gateway'
      description__value: null
      description__format: null
      weight: '2'
      parent: '2'
      uuid: 6a39f944-2b70-440a-9f2f-574583eb5b85
    -
      vid: portfolios
      tid: '14'
      langcode: en
      name: 'VMware Solutions on IBM Cloud'
      description__value: null
      description__format: null
      weight: '10'
      parent: '6'
      uuid: d7b5f3ba-eb48-4385-a946-582c64df1979
    -
      vid: portfolios
      tid: '15'
      langcode: en
      name: 'IBM StoredIQ'
      description__value: null
      description__format: null
      weight: '0'
      parent: '4'
      uuid: 61d3c814-1edc-45f4-b077-98920a9352b0
    -
      vid: portfolios
      tid: '16'
      langcode: en
      name: 'IBM App Connect'
      description__value: null
      description__format: null
      weight: '5'
      parent: '2'
      uuid: 6a47f01f-88fd-47ef-a8d0-ff492c8cd067
    -
      vid: portfolios
      tid: '17'
      langcode: en
      name: 'IBM DB2 Warehouse on Cloud'
      description__value: null
      description__format: null
      weight: '1'
      parent: '1'
      uuid: c5955b38-20d6-409e-b0fc-26279870584b
    -
      vid: portfolios
      tid: '18'
      langcode: en
      name: 'IBM SPSS Modeler'
      description__value: null
      description__format: null
      weight: '8'
      parent: '5'
      uuid: e738167a-6307-4d4b-bd6c-1d4be1c9a05a
    -
      vid: portfolios
      tid: '19'
      langcode: en
      name: 'IBM MQ on Cloud'
      description__value: null
      description__format: null
      weight: '1'
      parent: '2'
      uuid: 470b1db0-d5fe-40b4-8ac3-f39dfb43d46f
    -
      vid: portfolios
      tid: '20'
      langcode: en
      name: 'IBM DataStage'
      description__value: null
      description__format: null
      weight: '2'
      parent: '4'
      uuid: 65dbc34c-1d58-4474-a4fa-0f57c2c1ae5f
    -
      vid: portfolios
      tid: '21'
      langcode: en
      name: 'IBM Planning Analytics'
      description__value: null
      description__format: null
      weight: '7'
      parent: '5'
      uuid: 1e4fdfa7-7ba4-41e6-86cd-0a286c127dd2
    -
      vid: portfolios
      tid: '22'
      langcode: en
      name: 'IBM Integrated Analytics System'
      description__value: null
      description__format: null
      weight: '2'
      parent: '1'
      uuid: b0e0782b-08e3-4e12-9b4b-bd9cee26ab63
    -
      vid: portfolios
      tid: '23'
      langcode: en
      name: 'IBM Aspera on Cloud'
      description__value: null
      description__format: null
      weight: '0'
      parent: '2'
      uuid: f114c304-2550-4ed1-83be-bbb44d8d30ef
    -
      vid: portfolios
      tid: '24'
      langcode: en
      name: 'IBM SPSS Statistics'
      description__value: null
      description__format: null
      weight: '9'
      parent: '5'
      uuid: 5a2c970b-d701-4b85-97b4-3ea482d252af
    -
      vid: portfolios
      tid: '25'
      langcode: en
      name: 'SAP HANA in the IBM Cloud'
      description__value: null
      description__format: null
      weight: '9'
      parent: '6'
      uuid: 7be7caa0-d33c-4935-a6c1-1fa773fe3891
    -
      vid: portfolios
      tid: '26'
      langcode: en
      name: 'IBM App Connect Professional'
      description__value: null
      description__format: null
      weight: '6'
      parent: '2'
      uuid: 63a929e2-d795-45f3-beca-c554b7e59313
    -
      vid: portfolios
      tid: '27'
      langcode: en
      name: 'IBM App Connect Enterprise'
      description__value: null
      description__format: null
      weight: '3'
      parent: '2'
      uuid: d31ba721-f2e6-4714-aab6-8a28dad89e53
    -
      vid: portfolios
      tid: '28'
      langcode: en
      name: 'IBM DB2 Big SQL'
      description__value: null
      description__format: null
      weight: '3'
      parent: '5'
      uuid: fccf0492-ca67-49e1-8bfd-1950d38c0411
    -
      vid: portfolios
      tid: '29'
      langcode: en
      name: 'IBM ILOG CPLEX Optimization Studio'
      description__value: null
      description__format: null
      weight: '4'
      parent: '5'
      uuid: 029ae8d7-408c-4b10-af44-84be74c2c488
    -
      vid: portfolios
      tid: '30'
      langcode: en
      name: 'IBM Cognos Analytics'
      description__value: null
      description__format: null
      weight: '0'
      parent: '5'
      uuid: 9b06569b-e802-42b9-92f5-b6f8592c2eab
    -
      vid: portfolios
      tid: '31'
      langcode: en
      name: 'IBM Db2'
      description__value: null
      description__format: null
      weight: '0'
      parent: '1'
      uuid: 4f3ffe8a-8ebc-48a5-965e-f1de46e110c0
    -
      vid: portfolios
      tid: '32'
      langcode: en
      name: 'IBM Information Governance Catalog'
      description__value: null
      description__format: null
      weight: '5'
      parent: '5'
      uuid: 17c89a7b-5486-450e-8a85-5cce67b6374d
    -
      vid: portfolios
      tid: '33'
      langcode: en
      name: 'IBM InfoSphere Optim Test Data Fabrication'
      description__value: null
      description__format: null
      weight: '6'
      parent: '5'
      uuid: 8e16217e-4a81-4c38-9e41-f4895d0be6a8
    -
      vid: portfolios
      tid: '34'
      langcode: en
      name: 'IBM Blueworks Live'
      description__value: null
      description__format: null
      weight: '0'
      parent: '7'
      uuid: 1d70cd2c-c02f-42ec-90b6-f83055a1b37a
    -
      vid: portfolios
      tid: '35'
      langcode: en
      name: 'IBM Robotic Process Automation'
      description__value: null
      description__format: null
      weight: '1'
      parent: '7'
      uuid: 044e94d6-51bb-4aad-b31b-4c40a4178821
    -
      vid: portfolios
      tid: '36'
      langcode: en
      name: 'IBM Watson Explorer'
      description__value: null
      description__format: null
      weight: '1'
      parent: '5'
      uuid: acb6f47a-aaa0-4a5c-9591-7c3af53d6ed8
    -
      vid: portfolios
      tid: '37'
      langcode: en
      name: 'IBM Watson Knowledge Catalog'
      description__value: null
      description__format: null
      weight: '5'
      parent: '6'
      uuid: 952938c6-10a8-48d8-a924-9dbd0c991028
    -
      vid: portfolios
      tid: '38'
      langcode: en
      name: 'IBM Watson Studio'
      description__value: null
      description__format: null
      weight: '6'
      parent: '6'
      uuid: 43e577be-1617-4311-b4da-f4404010137e
    -
      vid: portfolios
      tid: '39'
      langcode: en
      name: 'IBM Watson Assistant'
      description__value: null
      description__format: null
      weight: '3'
      parent: '6'
      uuid: 8fd3cfaa-f0da-4fb0-bfae-04acb805d073
    -
      vid: portfolios
      tid: '40'
      langcode: en
      name: 'IBM Watson Discovery'
      description__value: null
      description__format: null
      weight: '4'
      parent: '6'
      uuid: fe388f62-8f35-451f-a3bd-ab085e67c3f8
    -
      vid: portfolios
      tid: '41'
      langcode: en
      name: 'IBM Watson Studio Machine Learning'
      description__value: null
      description__format: null
      weight: '7'
      parent: '6'
      uuid: 360b4211-c780-4248-9efd-b894bd3b53ee
    -
      vid: portfolios
      tid: '42'
      langcode: en
      name: 'IBM Watson Visual Recognition'
      description__value: null
      description__format: null
      weight: '8'
      parent: '6'
      uuid: e52deb4b-36dd-461b-a4d5-727c9287badc
    -
      vid: portfolios
      tid: '43'
      langcode: en
      name: 'IBM Dynamic Dashboard Embedded'
      description__value: null
      description__format: null
      weight: '0'
      parent: '6'
      uuid: 7ea439d3-d0a5-4d97-9bbc-238b2806232b
    -
      vid: portfolios
      tid: '44'
      langcode: en
      name: 'IBM ICOS'
      description__value: null
      description__format: null
      weight: '1'
      parent: '6'
      uuid: 84f835f4-eb6f-48e8-b9c4-c0907b5d1bca
    -
      vid: portfolios
      tid: '45'
      langcode: en
      name: 'IBM Virtual Router Appliance'
      description__value: null
      description__format: null
      weight: '2'
      parent: '6'
      uuid: 579325c4-2af1-47df-8e07-25eb6fe034d5
    -
      vid: portfolios
      tid: '46'
      langcode: en
      name: 'Zerto on IBM Cloud'
      description__value: null
      description__format: null
      weight: '11'
      parent: '6'
      uuid: de8d865d-20fa-4b36-97bf-238fd795f2f0
  programming_runtimes: {  }
