overview_left: 'workbench_edited:block_2'
overview_right: 'workbench_edited:block_3'
overview_main: 'workbench_content_in_moderation_by_user:block_1'
edits_main: 'workbench_edited:embed_1'
all_main: 'workbench_recent_content:embed_1'
_core:
  default_config_hash: aGR45_bxRagev3Ecuwgjvr3x2Ccgsmsk-Evv-SIkwQM
